server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/api?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: 
        password: 
    jpa:
        show-sql: true

endpoints:
    shutdown:
        sensitive: false
        enabled: true

management:
    address: 127.0.0.1
    port: 9000
    security:
        enabled: false

com:
    mtdhb:
        api:
            nodejs:
                url: http://127.0.0.1:3333
                check-cookie: /check-cookie
                get-hongbao: /get-hongbao
            mail:
                register-mail-subject: 一键领取手气最佳红包-注册
                register-mail-effective-time: 30
                reset-password-mail-subject: 一键领取手气最佳红包-重置密码
                reset-password-mail-effective-time: 30
                blacklist:
                    # http://www.bccto.me/
                    - bccto.me
                    - jnpayy.com
                    - 11163.com
                    - chaichuang.com
                    - a7996.com
                    - dawin.com
                    - 4059.com
                    - 3202.com
                    - 4057.com
                    - ytpayy.com
                    - juyouxi.com
                    - meihuajun76.com
                    - cuirushi.org
                    - zymuying.com
                    - zhaoyuanedu.cn
                    - dhy.cc
                    - cr219.com
                    - mdu.edu.rs
                    - mail.jpgames.net
                    - dongqing365.com
                    - dahongying.net
                    # http://24mail.chacuo.net/
                    - chacuo.net
                    - 027168.com
                    # http://www.yopmail.com/zh/
                    - yopmail.com
                    # https://10minutemail.org/
                    - kpooa.com